export const ownerDashboardData = {
  welcome: {
    name: "Mr. Wilson",
    message: "Here's your business overview and key performance metrics",
    dateTime: "Sunday, August 3rd, 2025 - 11:00 PM",
  },
  alerts: [
    {
      type: "info",
      icon: "📈",
      message:
        "Great News: Monthly revenue is up 15.2% compared to last month with ₹18,450 total collection.",
    },
    {
      type: "warning",
      icon: "⚠️",
      message:
        "Attention Required: 5 members have outstanding dues totaling ₹2,500. Consider follow-up actions.",
    },
  ],
  kpis: [
    {
      label: "Monthly Revenue",
      value: "₹18,450",
      change: "+15.2% from last month",
      trend: "positive",
    },
    {
      label: "Active Members",
      value: "45",
      change: "+2 new members",
      trend: "positive",
    },
    {
      label: "Collection Efficiency",
      value: "89%",
      change: "+3.2% improvement",
      trend: "positive",
    },
    {
      label: "Total Books",
      value: "247",
      change: "+12 added this month",
      trend: "positive",
    },
    {
      label: "Books in Circulation",
      value: "89",
      change: "Steady usage",
      trend: "neutral",
    },
    {
      label: "Asset Value",
      value: "₹2,85,000",
      change: "+4.8% growth",
      trend: "positive",
    },
  ],
  quickActions: [
    {
      title: "Financial Reports",
      description: "Revenue & cost analysis",
      screen: "FinancialReports",
    },
    {
      title: "Asset Reports",
      description: "Inventory valuation",
      screen: "AssetReports",
    },
    {
      title: "Collection Reports",
      description: "Fee & fine analytics",
      screen: "CollectionReports",
    },
    {
      title: "User Statistics",
      description: "Member analytics",
      screen: "UserStatistics",
    },
    {
      title: "Subject Analysis",
      description: "Collection breakdown",
      screen: "SubjectWiseInventory",
    },
    {
      title: "Book Analysis",
      description: "Copy utilization",
      screen: "BookWiseCopies",
    },
  ],
  keyBusinessMetrics: [
    { label: "Avg Revenue/Member:", value: "₹410" },
    { label: "Member Retention Rate:", value: "94.2%" },
    { label: "Book Utilization:", value: "76.3%" },
    { label: "Operating Margin:", value: "68.5%" },
    { label: "ROI on Books:", value: "23.4%" },
    { label: "Avg Books/Member:", value: "5.5" },
  ],
  thisMonthSummary: [
    { label: "New Members:", value: "2" },
    { label: "Books Added:", value: "12" },
    { label: "Total Transactions:", value: "156" },
    { label: "Fine Collections:", value: "₹2,950" },
    { label: "Outstanding Dues:", value: "₹2,500" },
  ],
  performanceTargets: [
    { label: "Monthly Revenue Target:", value: "103% ✓", status: "positive" },
    { label: "Member Growth Target:", value: "104% ✓", status: "positive" },
    { label: "Collection Efficiency:", value: "89% ⚠", status: "neutral" },
    { label: "Book Utilization:", value: "98% ✓", status: "positive" },
  ],
  revenueTrendChartData:
    "Jan: ₹15,200 | Feb: ₹16,100 | Mar: ₹17,300 | Apr: ₹16,800 | May: ₹17,900 | Jun: ₹18,450",
};

export const userStatisticsData = {
  overview: [
    {
      label: "Total Members",
      value: "45",
      change: "+2 this month",
      trend: "positive",
    },
    {
      label: "Active Members",
      value: "38",
      change: "84.4% of total",
      trend: "neutral",
    },
    {
      label: "Inactive Members",
      value: "7",
      change: "15.6% of total",
      trend: "negative",
    },
    {
      label: "New This Month",
      value: "2",
      change: "100% growth target",
      trend: "positive",
    },
    {
      label: "Retention Rate",
      value: "94.2%",
      change: "+2.1% improvement",
      trend: "positive",
    },
    {
      label: "Avg Books/Member",
      value: "5.5",
      change: "+0.3 from last month",
      trend: "positive",
    },
  ],
  memberActivityTable: [
    {
      level: "High Activity (10+ books)",
      members: "12",
      percentage: "26.7%",
      avgBooks: "14.5",
      totalRevenue: "₹6,000",
      avgRevenue: "₹500",
    },
    {
      level: "Medium Activity (5-9 books)",
      members: "18",
      percentage: "40.0%",
      avgBooks: "7.2",
      totalRevenue: "₹9,000",
      avgRevenue: "₹500",
    },
    {
      level: "Low Activity (1-4 books)",
      members: "8",
      percentage: "17.8%",
      avgBooks: "2.8",
      totalRevenue: "₹4,000",
      avgRevenue: "₹500",
    },
    {
      level: "Inactive (0 books)",
      members: "7",
      percentage: "15.6%",
      avgBooks: "0",
      totalRevenue: "₹3,500",
      avgRevenue: "₹500",
    },
    {
      level: "Total",
      members: "45",
      percentage: "100%",
      avgBooks: "5.5",
      totalRevenue: "₹22,500",
      avgRevenue: "₹500",
    },
  ],
  memberGrowthTrendData:
    "Aug 2024: 35 | Dec 2024: 38 | Apr 2025: 41 | Aug 2025: 45",
  memberGrowthTrendDetails: "Steady Growth: +2.8% monthly average",
  memberInsights: [
    { label: "Most Active Member:", value: "John Doe (28 books)" },
    { label: "Average Age:", value: "32 years" },
    { label: "Gender Split:", value: "58% M / 42% F" },
    { label: "Average Visit Duration:", value: "45 minutes" },
    { label: "Peak Activity Day:", value: "Saturday" },
  ],
  engagementMetrics: [
    { label: "Avg Session Duration:", value: "1.2 hours" },
    { label: "Books per Visit:", value: "2.3" },
    { label: "Return Rate:", value: "98.5%" },
    { label: "Late Return Rate:", value: "12.8%" },
    { label: "Member Satisfaction:", value: "4.6/5.0" },
  ],
  revenueAnalysis: [
    { label: "Total Revenue/Month:", value: "₹22,500", trend: "neutral" },
    { label: "Revenue per Member:", value: "₹500", trend: "neutral" },
    { label: "Late Fee Revenue:", value: "₹2,950", trend: "neutral" },
    { label: "Revenue Growth:", value: "+15.2%", trend: "positive" },
  ],
  recentActivity: [
    {
      member: "Alice Smith (LIB001235)",
      details: "Joined library - Welcome package provided",
      time: "2 hours ago",
    },
    {
      member: "John Doe (LIB001234)",
      details: "Borrowed 3 books - Clean Code, Design Patterns, Refactoring",
      time: "4 hours ago",
    },
    {
      member: "Robert Johnson (LIB001025)",
      details: "Payment collected - Monthly fee + fine (₹640)",
      time: "6 hours ago",
    },
    {
      member: "Maria Garcia (LIB001087)",
      details: "Returned book - The Pragmatic Programmer",
      time: "8 hours ago",
    },
    {
      member: "David Wilson (LIB001156)",
      details: "Book reservation - JavaScript: The Good Parts",
      time: "1 day ago",
    },
  ],
};

export const subjectWiseInventoryData = {
  overview: [
    { label: "Subject Categories", value: "8" },
    { label: "Total Book Titles", value: "247" },
    { label: "Total Copies", value: "456" },
    { label: "Available Copies", value: "158" },
    { label: "Currently Issued", value: "89" },
    { label: "Avg Utilization", value: "76.3%" },
  ],
  subjects: [
    {
      name: "Programming",
      titles: "89",
      totalCopies: "156",
      available: "67",
      issued: "89",
      utilization: "85.2%",
      totalValue: "₹89,500",
      avgPrice: "₹1,006",
      growthRate: "+12.5%",
      popularBooks: "45 titles",
    },
    {
      name: "Science",
      titles: "67",
      totalCopies: "134",
      available: "56",
      issued: "78",
      utilization: "78.3%",
      totalValue: "₹67,200",
      avgPrice: "₹1,003",
      growthRate: "+8.3%",
      popularBooks: "32 titles",
    },
    {
      name: "Literature",
      titles: "45",
      totalCopies: "90",
      available: "32",
      issued: "58",
      utilization: "64.4%",
      totalValue: "₹36,000",
      avgPrice: "₹800",
      growthRate: "+5.2%",
      popularBooks: "28 titles",
    },
    {
      name: "History",
      titles: "28",
      totalCopies: "56",
      available: "21",
      issued: "35",
      utilization: "58.9%",
      totalValue: "₹22,400",
      avgPrice: "₹800",
      growthRate: "+3.7%",
      popularBooks: "18 titles",
    },
    {
      name: "Mathematics",
      titles: "18",
      totalCopies: "36",
      available: "20",
      issued: "16",
      utilization: "44.4%",
      totalValue: "₹21,600",
      avgPrice: "₹1,200",
      growthRate: "+2.1%",
      popularBooks: "8 titles",
    },
  ],
  summaryTable: [
    {
      subject: "Programming",
      books: "89",
      copies: "156",
      available: "67",
      issued: "89",
      utilization: "85.2%",
      totalValue: "₹89,500",
      avgPrice: "₹1,006",
    },
    {
      subject: "Science",
      books: "67",
      copies: "134",
      available: "56",
      issued: "78",
      utilization: "78.3%",
      totalValue: "₹67,200",
      avgPrice: "₹1,003",
    },
    {
      subject: "Literature",
      books: "45",
      copies: "90",
      available: "32",
      issued: "58",
      utilization: "64.4%",
      totalValue: "₹36,000",
      avgPrice: "₹800",
    },
    {
      subject: "History",
      books: "28",
      copies: "56",
      available: "21",
      issued: "35",
      utilization: "58.9%",
      totalValue: "₹22,400",
      avgPrice: "₹800",
    },
    {
      subject: "Mathematics",
      books: "18",
      copies: "36",
      available: "20",
      issued: "16",
      utilization: "44.4%",
      totalValue: "₹21,600",
      avgPrice: "₹1,200",
    },
    {
      subject: "TOTAL",
      books: "247",
      copies: "472",
      available: "196",
      issued: "276",
      utilization: "58.5%",
      totalValue: "₹2,36,700",
      avgPrice: "₹958",
    },
  ],
};

export const bookWiseCopiesData = {
  overview: [
    { label: "Total Book Titles", value: "247" },
    { label: "Total Copies", value: "456" },
    { label: "Avg Copies/Book", value: "1.85" },
    { label: "Available Copies", value: "158" },
    { label: "Issued Copies", value: "89" },
    { label: "Avg Utilization", value: "65.4%" },
  ],
  books: [
    {
      title: "Clean Code: A Handbook of Agile Software Craftsmanship",
      author: "Robert C. Martin",
      subject: "Programming",
      totalCopies: "5",
      available: "3",
      issued: "2",
      utilization: "85%",
      bookValue: "₹2,499",
      totalInvestment: "₹12,495",
    },
    {
      title: "The Pragmatic Programmer",
      author: "Andrew Hunt & David Thomas",
      subject: "Programming",
      totalCopies: "4",
      available: "1",
      issued: "3",
      utilization: "92%",
      bookValue: "₹2,299",
      totalInvestment: "₹9,196",
    },
    {
      title: "JavaScript: The Good Parts",
      author: "Douglas Crockford",
      subject: "Programming",
      totalCopies: "6",
      available: "4",
      issued: "2",
      utilization: "72%",
      bookValue: "₹1,899",
      totalInvestment: "₹11,394",
    },
    {
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
      author: "Gang of Four",
      subject: "Programming",
      totalCopies: "3",
      available: "1",
      issued: "2",
      utilization: "89%",
      bookValue: "₹2,799",
      totalInvestment: "₹8,397",
    },
    {
      title: "Physics: Concepts and Connections",
      author: "Art Hobson",
      subject: "Science",
      totalCopies: "4",
      available: "2",
      issued: "2",
      utilization: "65%",
      bookValue: "₹3,299",
      totalInvestment: "₹13,196",
    },
    {
      title: "Pride and Prejudice",
      author: "Jane Austen",
      subject: "Literature",
      totalCopies: "2",
      available: "1",
      issued: "1",
      utilization: "58%",
      bookValue: "₹599",
      totalInvestment: "₹1,198",
    },
    {
      title: "Advanced Mathematics for Engineering Students",
      author: "G. Stephenson",
      subject: "Mathematics",
      totalCopies: "2",
      available: "2",
      issued: "0",
      utilization: "25%",
      bookValue: "₹1,899",
      totalInvestment: "₹3,798",
    },
  ],
};

export const financialReportsData = {
  overview: [
    {
      label: "Monthly Revenue",
      value: "₹18,450",
      change: "+15.2% from last month",
      trend: "positive",
    },
    {
      label: "Monthly Expenses",
      value: "₹5,750",
      change: "-3.8% from last month",
      trend: "negative",
    },
    {
      label: "Net Profit",
      value: "₹12,700",
      change: "+24.1% from last month",
      trend: "positive",
    },
    {
      label: "Profit Margin",
      value: "68.8%",
      change: "+5.3% improvement",
      trend: "positive",
    },
    {
      label: "Total Assets",
      value: "₹2,85,000",
      change: "+4.8% growth",
      trend: "positive",
    },
  ],
  revenueExpenseTable: [
    {
      category: "Membership Fees",
      thisMonth: "₹15,500",
      lastMonth: "₹14,200",
      change: "+₹1,300",
      percentChange: "+9.2%",
    },
    {
      category: "Fine Collections",
      thisMonth: "₹2,950",
      lastMonth: "₹2,000",
      change: "+₹950",
      percentChange: "+47.5%",
    },
    {
      category: "Total Revenue",
      thisMonth: "₹18,450",
      lastMonth: "₹16,200",
      change: "+₹2,250",
      percentChange: "+13.9%",
    },
    {
      category: "Staff Salaries",
      thisMonth: "₹3,500",
      lastMonth: "₹3,500",
      change: "₹0",
      percentChange: "0%",
    },
    {
      category: "Book Acquisitions",
      thisMonth: "₹1,200",
      lastMonth: "₹2,100",
      change: "-₹900",
      percentChange: "-42.9%",
    },
    {
      category: "Utilities & Maintenance",
      thisMonth: "₹800",
      lastMonth: "₹750",
      change: "+₹50",
      percentChange: "+6.7%",
    },
    {
      category: "Other Expenses",
      thisMonth: "₹250",
      lastMonth: "₹300",
      change: "-₹50",
      percentChange: "-16.7%",
    },
    {
      category: "Total Expenses",
      thisMonth: "₹5,750",
      lastMonth: "₹6,650",
      change: "-₹900",
      percentChange: "-13.5%",
    },
    {
      category: "NET PROFIT",
      thisMonth: "₹12,700",
      lastMonth: "₹9,550",
      change: "+₹3,150",
      percentChange: "+33.0%",
    },
  ],
  keyFinancialRatios: [
    { label: "Profit Margin:", value: "68.8%" },
    { label: "Revenue Growth:", value: "+13.9%" },
    { label: "Cost Control:", value: "-13.5%" },
    { label: "ROI:", value: "24.3%" },
    { label: "Break-even Point:", value: "₹5,750" },
  ],
  cashFlowAnalysis: [
    { label: "Opening Balance:", value: "₹45,200" },
    { label: "Cash Inflow:", value: "₹18,450" },
    { label: "Cash Outflow:", value: "₹5,750" },
    { label: "Net Cash Flow:", value: "₹12,700" },
    { label: "Closing Balance:", value: "₹57,900" },
  ],
  performanceTargets: [
    { label: "Revenue Target:", value: "103% ✓", status: "positive" },
    { label: "Profit Target:", value: "108% ✓", status: "positive" },
    { label: "Cost Target:", value: "96% ✓", status: "positive" },
    { label: "Growth Target:", value: "114% ✓", status: "positive" },
  ],
  plTrendChartData:
    "Mar: ₹8,200 | Apr: ₹9,100 | May: ₹10,300 | Jun: ₹9,800 | Jul: ₹11,200 | Aug: ₹12,700",
};

export const collectionReportsData = {
  overview: [
    {
      label: "Total Collections",
      value: "₹18,450",
      change: "+15.2% from last month",
      trend: "positive",
    },
    {
      label: "Membership Fees",
      value: "₹15,500",
      change: "+8.5% from last month",
      trend: "positive",
    },
    {
      label: "Fine Collections",
      value: "₹2,950",
      change: "+45.3% from last month",
      trend: "positive",
    },
    {
      label: "Collection Efficiency",
      value: "89.2%",
      change: "+3.1% improvement",
      trend: "positive",
    },
    {
      label: "Outstanding Dues",
      value: "₹2,500",
      change: "5 members pending",
      trend: "negative",
    },
  ],
  dailyCollectionTable: [
    {
      date: "Aug 3, 2025",
      membershipFees: "₹2,500",
      fineCollections: "₹185",
      totalCollected: "₹2,685",
      transactions: "8",
      efficiency: "92.3%",
    },
    {
      date: "Aug 2, 2025",
      membershipFees: "₹3,000",
      fineCollections: "₹95",
      totalCollected: "₹3,095",
      transactions: "12",
      efficiency: "89.1%",
    },
    {
      date: "Aug 1, 2025",
      membershipFees: "₹2,000",
      fineCollections: "₹140",
      totalCollected: "₹2,140",
      transactions: "9",
      efficiency: "85.6%",
    },
    {
      date: "Jul 31, 2025",
      membershipFees: "₹1,500",
      fineCollections: "₹75",
      totalCollected: "₹1,575",
      transactions: "6",
      efficiency: "88.2%",
    },
    {
      date: "Jul 30, 2025",
      membershipFees: "₹3,500",
      fineCollections: "₹250",
      totalCollected: "₹3,750",
      transactions: "15",
      efficiency: "94.5%",
    },
    {
      date: "Total (Last 5 Days)",
      membershipFees: "₹12,500",
      fineCollections: "₹745",
      totalCollected: "₹13,245",
      transactions: "50",
      efficiency: "89.9%",
    },
  ],
  collectionAnalysis: [
    { label: "Peak Collection Day:", value: "Jul 30 (₹3,750)" },
    { label: "Average Daily Collection:", value: "₹2,649" },
    { label: "Fee-to-Fine Ratio:", value: "84:16" },
    { label: "Collection Growth:", value: "+15.2%" },
    { label: "Best Performing Day:", value: "Tuesday" },
  ],
  outstandingAnalysis: [
    { label: "Total Outstanding:", value: "₹2,500" },
    { label: "Members with Dues:", value: "5" },
    { label: "Avg Outstanding/Member:", value: "₹500" },
    { label: "Overdue (>30 days):", value: "2 members" },
    { label: "Recovery Rate:", value: "89.2%" },
  ],
  performanceMetrics: [
    { label: "Monthly Target:", value: "103% ✓", status: "positive" },
    { label: "Efficiency Target:", value: "89% ⚠", status: "neutral" },
    { label: "Growth Target:", value: "114% ✓", status: "positive" },
    { label: "Fine Reduction Goal:", value: "156% ✗", status: "negative" },
  ],
  collectionDistributionChartData: [
    { label: "Membership Fees", value: "84.0%", amount: "₹15,500" },
    { label: "Fine Collections", value: "16.0%", amount: "₹2,950" },
  ],
};

export const assetReportsData = {
  overview: [
    {
      label: "Total Asset Value",
      value: "₹2,85,000",
      change: "+4.8% from last month",
      trend: "positive",
    },
    {
      label: "Total Books",
      value: "247",
      change: "+12 added this month",
      trend: "positive",
    },
    {
      label: "Total Copies",
      value: "456",
      change: "+18 added this month",
      trend: "positive",
    },
    {
      label: "Utilization Rate",
      value: "76.3%",
      change: "+2.1% improvement",
      trend: "positive",
    },
    {
      label: "Avg Book Value",
      value: "₹625",
      change: "Stable pricing",
      trend: "neutral",
    },
  ],
  valuationTable: [
    {
      category: "Programming Books",
      quantity: "89",
      totalValue: "₹89,500",
      avgValue: "₹1,006",
      utilization: "85%",
      growth: "+12.5%",
    },
    {
      category: "Science Books",
      quantity: "67",
      totalValue: "₹67,200",
      avgValue: "₹1,003",
      utilization: "78%",
      growth: "+8.3%",
    },
    {
      category: "Literature Books",
      quantity: "45",
      totalValue: "₹36,000",
      avgValue: "₹800",
      utilization: "65%",
      growth: "+5.2%",
    },
    {
      category: "History Books",
      quantity: "28",
      totalValue: "₹22,400",
      avgValue: "₹800",
      utilization: "58%",
      growth: "+3.7%",
    },
    {
      category: "Mathematics Books",
      quantity: "18",
      totalValue: "₹21,600",
      avgValue: "₹1,200",
      utilization: "45%",
      growth: "+2.1%",
    },
    {
      category: "Equipment",
      quantity: "12",
      totalValue: "₹35,000",
      avgValue: "₹2,917",
      utilization: "90%",
      growth: "0%",
    },
    {
      category: "Furniture",
      quantity: "25",
      totalValue: "₹13,300",
      avgValue: "₹532",
      utilization: "100%",
      growth: "0%",
    },
    {
      category: "TOTAL",
      quantity: "284",
      totalValue: "₹2,85,000",
      avgValue: "₹1,004",
      utilization: "76%",
      growth: "+7.2%",
    },
  ],
  assetPerformance: [
    { label: "Highest ROI Category:", value: "Programming" },
    { label: "Most Utilized:", value: "Furniture (100%)" },
    { label: "Fastest Growing:", value: "Programming (+12.5%)" },
    { label: "Needs Attention:", value: "Mathematics (45%)" },
    { label: "Depreciation Rate:", value: "8.5% annually" },
  ],
  investmentAnalysis: [
    { label: "Total Investment:", value: "₹2,85,000" },
    { label: "Annual Depreciation:", value: "₹24,225" },
    { label: "Net Book Value:", value: "₹2,60,775" },
    { label: "Replacement Cost:", value: "₹3,20,000" },
    { label: "Insurance Value:", value: "₹2,75,000" },
  ],
  maintenanceSchedule: [
    { label: "Due This Month:", value: "8 items" },
    { label: "Overdue Maintenance:", value: "2 items" },
    { label: "Upcoming (3 months):", value: "15 items" },
    { label: "Maintenance Budget:", value: "₹5,200/month" },
  ],
  valuationTrendChartData:
    "Aug 2024: ₹2,42,000 | Dec 2024: ₹2,58,000 | Apr 2025: ₹2,71,000 | Aug 2025: ₹2,85,000",
};
